test_that("linear Regression", {
  model.fit <- blblm(mpg ~ wt * hp, data = mtcars, m = 3, B = 100)
  coefficiences <- coef( model.fit)
  confidence_interval <- confint(model.fit, c("wt", "hp"))
  sigma_boot <- sigma( model.fit, confidence = TRUE)
  prediction <- predict(model.fit, data.frame(wt = c(2.5, 3), hp = c(150, 170)))
  expect_s3_class(model.fit, 'blblm')
  expect_equal(length(coefficiences),4)
  expect_equal(length(confidence_interval),4)
  expect_equal(length(sigma_boot),3)
  expect_equal(length(prediction),2)
})

test_that("linear Regression parallel", {
  model.fit_paralle <- blblm_parallel(mpg ~ wt * hp, data = mtcars, m = 3, B = 100, core = 1)
  coefficiences <- coef(model.fit_paralle)
  confidence_interval <- confint(model.fit_paralle, c("wt", "hp"))
  sigma_boot <- sigma(model.fit_paralle, confidence = TRUE)
  prediction <- predict(model.fit_paralle, data.frame(wt = c(2.5, 3), hp = c(150, 170)))
  expect_s3_class(model.fit_paralle, 'blblm')
  expect_equal(length(coefficiences),4)
  expect_equal(length(confidence_interval),4)
  expect_equal(length(sigma_boot),3)
  expect_equal(length(prediction),2)
})

test_that("linear Regression furrr", {
  model.fit_furrr <- blblm_furrr(mpg ~ wt * hp, data = mtcars, m = 3, B = 100)
  coefficiences <- coef(model.fit_furrr)
  confidence_interval <- confint(model.fit_furrr, c("wt", "hp"))
  sigma_boot <- sigma(model.fit_furrr, confidence = TRUE)
  prediction <- predict(model.fit_furrr, data.frame(wt = c(2.5, 3), hp = c(150, 170)))
  expect_s3_class(model.fit_furrr, 'blblm')
  expect_equal(length(coefficiences),4)
  expect_equal(length(confidence_interval),4)
  expect_equal(length(sigma_boot),3)
  expect_equal(length(prediction),2)
})